### PR TITLE
Weather Underground

### PR DESCRIPTION
**Pull request by rayvenwalker**
Added state field.

### CODE REVIEW

**Comment by ualex73** [comment]
@Alex: can you tell me which city/town are you search for in the Weather Underground? I like to test it too :-)

**Comment by rayvenwalker** [comment]
USA/KY/Flatwoods

I did not test this without the State field.  Possibly we could add a case
switch to look for USA and then State.

**Comment by ualex73** [comment]
Thanks, i will do some testing tonight and submit a fix for it ... (i will test with American and Europe cities)

**Comment by rayvenwalker** [comment]
Great, I figured I'd start with a few lines of code.  This is my first
experience with opensource.  Should I be working on the beta branch?

I have some other larger bits of code for, DomoWrapper that adds more
support for a CT-101 Thermostat(no control yet tho), MySensors Plugin(I
used variable 99 to store the V_LIGHT descriptor), UPS Plugin add more
values for a APC BackUPS.

I also have had some preliminary work started on a XBee/ZigBee Interface.

**Comment by ualex73** [comment]
Very good to hear you are coding too to enhance/bugfix things :-)

Yes - you should write the code against the BETA branch. Once in a while, we merge it in the MASTER. The key is here, none-DB changes we can sync also to the MASTER, but if there are DB changes, we need to make it a new release (which we don't want to do weekly ;-)).

If you require any DB changes soon, please let us know, we want to merge the current BETA reasonable soon in the MASTER. Your code doesn't have to be 100% finished, aslong we got the DB stuff done :-)

**Comment by ualex73** [comment]
I had time to investigate it, and i committed a change/fix for it in the BETA (similar like yours, but it does an additional check if the "state" is there or not).

https://github.com/DomotiGa/DomotiGa/commit/66f61697aa46ca0c70f451632e052ad3452dbf76

**Comment by rayvenwalker** [comment]
Awesome!

**Pull request closed without merging**
