### PR TITLE
Updates MySensors SendCommand

### PR DESCRIPTION
**Pull request by rayvenwalker**
Used Device Value99 to store Sensor Type for SendCommand function.
Parsed ChildID from device address.

### CODE REVIEW

**Comment by jessekerkhoven** [comment]
I added in 16e1a8b the missing description field in the device value editor. It was only available in DomotiYii. Value 99 can theoretically be used by MySensor it self so it wouldn't be a nice solution, we are currently working on the device value types in the valuetypes branch for this kind of problems. Personally i ordered some hardware to start with MySensors this week, so i will dive in to it. Thanks for your contribution, please add merge request next time to the beta branch and don't mix it with other test commits or topics.

**Comment by rayvenwalker** [comment]
Thanks for the feedback.  Just so I'm clear...  If i wanted to submit my changes to  domozwave.cpp for review regarding values for some new ZWave devices; Thermostat CT-101, ZSMOKE, ZCOMBO?  I modify the files on my end then commit the changes to my branch and submit a pull request (to the beta branch)?  Is this correct?

**Comment by jessekerkhoven** [comment]
Yes, please create a pull request to the beta branch

**Comment by ualex73** [comment]
@Ray:

I have implemented the DomoZWave.cpp into the BETA branch ... Except for the command class alarm, because it should work in theory (but it doesn't seem too - so i need to investigate it further)

**Comment by ualex73** [comment]
@Ray:

Looking into the feature to able to send values to MySensors - lets see if we can make it flexible/easy ;)

**Pull request closed without merging**
